name: "SPDX SBOM"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up pyenv
      run: |
        # Install dependencies for pyenv
        sudo apt-get update
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
                                libreadline-dev libsqlite3-dev wget curl llvm \
                                libncurses5-dev libncursesw5-dev xz-utils tk-dev \
                                libffi-dev liblzma-dev python-openssl git

        # Install pyenv
        curl https://pyenv.run | bash
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV

    - name: Initialize pyenv
      run: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"

        # Install the required Python version
        pyenv install 3.8.10
        pyenv global 3.8.10
        
        # Verify Python version
        python --version

    - name: Download and Install SBOM
      run: |
        curl -Lo $RUNNER_TEMP/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz https://github.com/spdx/spdx-sbom-generator/releases/download/v0.0.10/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz
        tar -xzf $RUNNER_TEMP/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz -C $RUNNER_TEMP
        chmod +x $RUNNER_TEMP/spdx-sbom-generator

    - name: Generate SBOM
      run: |
        mkdir SBOMOUTPUT
        $RUNNER_TEMP/spdx-sbom-generator -o SBOMOUTPUT
