name: "SPDX SBOM"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and Install SBOM
      run: |
        curl -Lo $RUNNER_TEMP/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz https://github.com/spdx/spdx-sbom-generator/releases/download/v0.0.10/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz
        tar -xzf $RUNNER_TEMP/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz -C $RUNNER_TEMP
        chmod +x $RUNNER_TEMP/spdx-sbom-generator
    - name: Generate SBOM
      run: |
        mkdir SBOMOUTPUT
        $RUNNER_TEMP/spdx-sbom-generator -o SBOMOUTPUT
