name: "SPDX SBOM"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing SBOM
      run: |
        curl -Lo $RUNNER_TEMP/spdx-sbom https://github.com/spdx/spdx-sbom-generator/releases/download/v0.0.10/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz
        chmod +x $RUNNER_TEMP/spdx-sbom

    - name: Generate SBOM
      run: |
        mkdir SBOMOUTPUT
        spdx-sbom -o SBOMOUTPUT 
